apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: simple
  name: simple
spec:
  replicas: 1
  selector:
    matchLabels:
      name: simple
  template:
    metadata:
      labels:
        name: simple
    spec:
      containers:
      - image: cloudnativeacr01.azurecr.io/simple:v2
        name: simple
        ports:
        - containerPort: 80