name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
    
jobs:

  build_push_image:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t cloudnativeacr01.azurecr.io/simple:v2 .
     
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: cloudnativeacr01
        # Container registry password
        password: mqQLbr9e0wwHnaEHM/AVaD2uMqvgdmXd
        # Container registry server url
        login-server: cloudnativeacr01.azurecr.io
        
    - name: Push Image  
      run: docker push cloudnativeacr01.azurecr.io/simple:v2
      
      
            
  deploy:
    runs-on: ubuntu-latest
    needs: build_push_image # Will wait for the execution of the previous job   
    steps:
    - uses: actions/checkout@v2
    - name: Kubernetes set context
      uses: Azure/k8s-set-context@v1
      with:
        kubeconfig: ${{secrets.KUBECONFIG}}  
      id: login

        
    - name: Kubernetes Deployment
      run: kubectl apply -f deploy.yaml
    - name: Service Deployment
      run: kubectl expose deployment simple --type=LoadBalancer --name=simple
